### ISSUE TITLE
bsdiff 4.3 tarball forbidden on daemonology.net

### ISSUE THREAD

**Issue by ghost** [cperciva/bsdiff#4]
Hi,
bsdiff is a dependency in openembedded-core layer. The tarball of version 4.3 of the software is returning 403 Forbidden: http://www.daemonology.net/bsdiff/bsdiff-4.3.tar.gz

Is that expected? Version 4.2 is available.

Thanks for the support.

**Comment by cperciva** [comment]
Yes.  There are security issues in that code; I've been pointing people at the code in FreeBSD instead (which has the fixes).
